### ISSUE TITLE
Subscribe to an Event

### ISSUE THREAD

**Issue by dashiwa** [dashiwa/DrupalAcquia#23]

**Comment by dashiwa** [comment]
### Подписка на события

**Определение сервиса, помеченного как 'event_subscriber'**
Определение класса для вашей абонентской службы, которая реализует 
`\Symfony\Component\EventDispatcher\EventSubscriberInterface`
и подписывается на одно или несколько событий

**Comment by dashiwa** [comment]
### Define an event subscriber service

Первое, что вам нужно сделать, это определить новый сервис, помеченный тегом «event_subscriber». 

Это делается в файле **{my_module} .services.yml** вашего модуля.

Пример

```
# Subscribing to an event requires you to create a new service tagged with the
# 'event_subscriber' tag. This tells the service container, and by proxy the
# event dispatcher service, that the class registered here can be queried to get
# a list of events that it would like to be notified about.
services:
  # Give your service a unique name, convention is to prefix service names with
  # the name of the module that implements them.
  events_example_subscriber:
    # Point to the class that will contain your implementation of
    # \Symfony\Component\EventDispatcher\EventSubscriberInterface
    class: Drupal\events_example\EventSubscriber\EventsExampleSubscriber
    tags:
      - {name: event_subscriber}
```


Это сделано для того, чтобы во время компиляции сервисного контейнера ваш класс подписчиков событий мог быть найден и использован для получения списка событий, на которые вы хотели бы подписаться. В качестве оптимизации производительности этот список затем компилируется в контейнер для более быстрого поиска в будущем.
