### ISSUE TITLE
Links: An Overview for Developers

### ISSUE THREAD

**Issue by dashiwa** [dashiwa/DrupalAcquia#33]
Drupal предоставляет разработчикам модулей несколько различных методов для создания различных типов ссылок, которые мы видим на типичной странице. 

**1. Menu links
2. Action links
3. Local tasks
4. Contextual links**

**Comment by dashiwa** [comment]
### Ссылки меню

**Comment by dashiwa** [comment]
### Add a Menu Item

Пример

```
page_example.description:
  title: Page Example
  route_name: page_example_description
  expanded: TRUE

page_example.simple:
  title: Simple - no arguments
  route_name: page_example_simple
  parent: page_example.description

# We can't define a menu link for the page_example_arguments route, because it
# requires path arguments.
```

Этот модуль содержит два пункта меню. Ключи в этом файле YAML являются уникальными именами  для каждого из пунктов меню, которые они определяют. 
Единственное значение, которое абсолютно необходимо, - **это заголовок,** хотя вы редко найдете элементы, которые также не содержат хотя бы a **route_name** или  **url**. 

Если пункт меню ссылается на внутренний маршрут, **route_name**  значение указывает маршрут Drupal для ссылки.

Внешний ресурс можно включить в меню, указав **url** вместо этого значение **route_name**.

**Comment by dashiwa** [comment]
### Изменение существующих пунктов меню

**Comment by dashiwa** [comment]
### Action links

Когда вы вошли в систему как администратор сайта, если вы натолкнулись на ссылку для добавления другого элемента, скорее всего, вы просматриваете ссылку действия. Ссылки действий позволяют разработчикам модулей предоставлять конкретные действия для работы со своими структурами данных.

Действия указаны в еще одном файле YAML с определенным соглашением об именах **.links.action.yml** . Снова используя модуль Node в качестве примера, вот содержимое файла `/core/modules/node/node.links.action.yml :`

```
node.type_add:
  route_name: node.type_add
  title: 'Add content type'
  appears_on:
    - entity.node_type.collection
node.add_page:
  route_name: node.add_page
  title: 'Add content'
  appears_on:
    - system.admin_content
```

**Comment by dashiwa** [comment]
### Contextual links

Контекстные ссылки предоставляют ярлыки для общих задач администратора. Например, при просмотре узла общие действия могут включать в себя редактирование или удаление контента. Контекстные ссылки, предоставляемые модулем узла, делают это проще.

Контекстные ссылки, в отличие от ссылок, которые мы рассматривали до сих пор, указываются не только через файл YAML. 

Контекстные ссылки должны идентифицировать конкретный маршрут (именованный путь URL), который будет использоваться в качестве контекстных ссылок. 
Эти маршруты перечислены в файле YAML с расширением .links.contextual.yml . В дополнение к файлу YAML контекстная ссылка должна добавить **#contextual_links** элемент в массив визуализации, где должна появиться ссылка.

Возвращаясь к модулю узла для примера, мы можем найти файл **/core/modules/node/node.links.contextual.yml :**

**Comment by dashiwa** [comment]
**Add a Contextual Link**

Contextual links YAML files

Модули, определяющие контекстные ссылки, должны предоставить файл `MODULE_NAME.links.contextual.yml` в каталоге верхнего уровня своего кода. Этот файл, как и все другие типы ссылок, содержит YAML-представление ссылок. Вот код из реализации контекстной ссылки модуля узла в `/core/modules/node/node.links.contextual.yml`

```
entity.node.edit_form:
  route_name: entity.node.edit_form
  group: node
  title: Edit

entity.node.delete_form:
  route_name: entity.node.delete_form
  group: node
  title: Delete
  weight: 10
```


Когда объект входит в цикл рендеринга, если #contextual_linksв массиве рендеринга есть элемент, то собирается соответствующая контекстная группа ссылок. Для блока соответствующая часть массива рендеринга может выглядеть так:

```
array(
  '#contextual_links' => array(
    'block' => array(
      'route_parameters' => array('block' => $entity->id()),
    ),
  ),
```

**block** Массив ключей в **#contextual_links** массиве определяет группу для контекстных ссылок , которые должны быть загружены.
 Ссылки для этой группы затем выводятся через конвейер рендеринга.
